uploaded vector
Dave11ar/first-term pull request #1
Opened 2020-06-27 14:21 UTC by Dave11ar

2020-06-27 14:54 UTC, kt-cpp requested changes

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +  }
[minor] Почему бы не использовать инициализацию членов класса?

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +    }
Удалять элементы стоит в обратном порядке и создания

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +      new(data_ + size_++) T(a);
Нарушена даже слабая гарантия, потому что в случае ошибки в конструкторе у тебя изменится `size_`, и вектор будет не оч валидным

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +    if (new_capacity < capacity_) return;
[minor] Не надо пожалуйста экономить на фигурных скобках. Это усложняет чтение кода и потенциально приводит к ошибкам. Таких место несколько по коду, пишу один раз

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +    for(int i = size_ - 1; i >= 0; i--) {
`int` мало. У тебя в векторе может быть как минимум `ptrdiff_t` элементов, а по хорошему `size_t`

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +  void clear() {
Почему бы не переиспользовать эту функцию в деструкторе? Тут и порядок деструкций правильный

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +  }
[minor] А почему не просто `erase(pos, pos + 1)`?

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +    for (int i = 0; i < erase_size; i++) {
Снова `int`

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +    reserve(increase_capacity());
При `push_back` в пустой вектор получается `capacity_ = 2 * 0 = 0`, а потом фиксится костылём в теле `reserve`. Это плохое дизайнерское решение, `reserve` не должна заниматься такими костылями, а иметь простой и понятный контракт

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +  }
Несмотря на строгую гарантию у этой функции довольно странный контракт и сомнительные части в духе ручного вызова деструктора вектора и принятия его первым аргументом по неконстантной ссылке. Пожалуйста переосмысли эту часть и то, как ты её используешь. К сожалению тут сложное дать подсказку, которая не является готовым решением в чистом виде. Могу лишь посоветовать разбить на части логику функции и посмотреть где в коде какие её части подойдут.

2020-06-27 14:54 UTC, kt-cpp commented on vector/vector.h
> +    new(data_ + size_++) T(tmp);
Тут тоже проблемы со строгой гарантией как и в публичном `push_back`

2020-06-27 16:35 UTC, Dave11ar commented on vector/vector.h
> +    }
А почему стоит именно так делать, или это просто хороший тон?

2020-06-28 07:17 UTC, kt-cpp requested changes
нужно исправить эти миноры. 1 старый комент не закрыл, чтобы посмотреть еще раз

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +    return std::max(2 * capacity_, (size_t)1);
[minor] как-то неприятно. если написать тернарник, то отпадает std::max и явный каст к size_t

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +    if (new_capacity < capacity_) {
<=

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +    size_t erase_size = last - first;
давай ptrdiff_t и проверку того, что отрезок не пуст

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +  size_t size_{};
для чего тебе {} ?

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +      for(i = size_; i > 0; i--) {
тут дважды копипаста clear(), подумай как сделать красиво, в 1 строчку

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +      data_ = new_data;
лишний код под try

2020-06-28 07:17 UTC, kt-cpp commented on vector/vector.h
> +  vector() : data_(nullptr), capacity_(0), size_(0) {}
посмотри на ворнинг компилятора. не стоит переупорядочивать

2020-06-28 13:59 UTC, kt-cpp commented on vector/vector.h
> +#include <cassert>
это уже видимо не нужно

2020-06-28 13:59 UTC, kt-cpp commented on vector/vector.h
> +    for(size_t i = size_; i > 0; i--) {
пробел

2020-06-28 14:00 UTC, kt-cpp commented on vector/vector.h
> +      data_[i - 1].~T();
Чуть-чуть можно переделать и сделать через ```pop_back()```

2020-06-28 14:02 UTC, kt-cpp approved these changes
Все хорошо

2020-06-28 14:02 UTC, merged