asm
Dave11ar/first-term pull request #2
Opened 2020-06-28 17:15 UTC by Dave11ar

2020-06-29 00:22 UTC, kt-cpp commented on asm/mul.asm
> +;    product is written to r9
Давай напишем в контракте, что в памяти по ```r9``` должно бьть ```rcx + 1``` qword

2020-06-29 00:23 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 4 * 128 * 8 + 129 * 8
Давай будем выделять 129 * 8 qword для ```tmp``` переменной в ```mul_long_long```

2020-06-29 00:23 UTC, kt-cpp commented on asm/mul.asm
> +                ;   r9 --- buffer for mul_long_short
Давай засунем это в контракт фукнции

2020-06-29 00:24 UTC, kt-cpp commented on asm/mul.asm
> +                ;   r9 --- buffer for mul_long_short
Ну т.е. кроме ```r10```, его в тело функции

2020-06-29 00:24 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rcx, [128 * 2]
```shl rcx, 1```

2020-06-29 00:27 UTC, kt-cpp commented on asm/mul.asm
> +                push            rdi
```rdi``` не портится, а ```rax``` мне лень было прослеживать, но кажется тоже нет

2020-06-29 00:28 UTC, kt-cpp commented on asm/mul.asm
> +                mov             r10, rcx
Может не будем это выделять как второй счетчик? Кажется можно везде сделать ```rcx```. Попробуй.

2020-06-29 00:28 UTC, kt-cpp requested changes
Давай немного дошлифуем код

2020-06-29 21:17 UTC, Dave11ar commented on asm/mul.asm
> +;    product is written to r9
fixed

2020-06-29 22:52 UTC, Dave11ar commented on asm/mul.asm
> +                mov             r10, rcx
fixed

2020-06-29 23:04 UTC, Dave11ar commented on asm/mul.asm
> +                sub             rsp, 4 * 128 * 8 + 129 * 8
fixed

2020-06-29 23:07 UTC, Dave11ar commented on asm/mul.asm
> +                ;   r9 --- buffer for mul_long_short
fixed

2020-06-29 23:14 UTC, Dave11ar commented on asm/mul.asm
> +                lea             rcx, [128 * 2]
fixed

2020-06-30 12:32 UTC, kt-cpp requested changes

2020-06-30 12:32 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 129 * 8
Какой-то хардкод, функция должна оперировать размером переданным в rcx

2020-06-30 12:32 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 128
Снова хардкод

2020-06-30 12:32 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 128
И снова хардкод

2020-06-30 12:32 UTC, kt-cpp commented on asm/mul.asm
> +;    sum is written to rdi
Неплохо добавить в контракт, что сумма имеет на 1 разряд больше

2020-06-30 12:32 UTC, kt-cpp commented on asm/mul.asm
> +                call            add_long_long
Несмотря на то, что ты внутри суммы увеличиваешь длину на 1, вообще-то говоря это семантически не правильно, ибо реальная длина первого аргумента 129, а не 128, ибо он получен в результате умножения. 
Плюс в таком случае у тебя складывается формально число длины 128 и 129, и ты почему-то утверждаешь, что их ответ влезет в длину 129.
В таком случае вопрос к тебе: правда ли это в данном случае и почему?

2020-06-30 13:45 UTC, Dave11ar commented on asm/mul.asm
> +                call            add_long_long
`Long` числа на стеке у нас лежат в системе счисления с основанием `256`. Самое больше число которое может получиться после `mul_long_short` --- ![equation](https://latex.codecogs.com/gif.latex?(256^{129}&space;-&space;1)255), тогда прибавим к нему самое большое `128 qword` число ---  ![equation](https://latex.codecogs.com/gif.latex?(256^{129}&space;-&space;1)), получим ![equation](https://latex.codecogs.com/gif.latex?256^{130}-256), что очевидно влезает в длину `129`

2020-06-30 14:22 UTC, Dave11ar commented on asm/mul.asm
> +                sub             rsp, 129 * 8
fixed

2020-06-30 14:22 UTC, Dave11ar commented on asm/mul.asm
> +                mov             rcx, 128
fixed

2020-06-30 14:22 UTC, Dave11ar commented on asm/mul.asm
> +                mov             rcx, 128
fixed

2020-06-30 14:23 UTC, Dave11ar commented on asm/mul.asm
> +;    sum is written to rdi
fixed

2020-06-30 14:43 UTC, kt-cpp commented on asm/mul.asm
> +                call            add_long_long
Открою секрет числа у тебя в основании `2 ^ 64`, а не `256`, потому что qword - это 8 байт, т.е. 64 бита. Но идейно доказательство сохранится

2020-06-30 14:46 UTC, kt-cpp commented on asm/mul.asm
> +                call            add_long_long
Хотя есть бага в оценке максимального размера результата умножения

2020-06-30 14:49 UTC, Dave11ar commented on asm/mul.asm
> +                call            add_long_long
Да я там перепутал, не 129 а 128 степень, аналогично не 130 а 129

2020-06-30 14:54 UTC, kt-cpp requested changes
Пофиксишь баги в доказательстве - примем

2020-06-30 15:12 UTC, kt-cpp approved these changes

2020-06-30 15:12 UTC, merged