Bigint
Dave11ar/first-term pull request #3
Opened 2020-06-28 23:21 UTC by Dave11ar

2020-06-30 07:52 UTC, kt-cpp requested changes
Я не все посмотрел, но тут и так есть что править
Потом может новые правки будут

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  sign(a < 0), value({a < 0 ? static_cast<uint32_t>(-static_cast<int64_t>(a)) : static_cast<uint32_t>(a)}) {}
[style] еле распарсил, пиши по понятнее, пожалуйста (уж value можно было не через member il)

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.h
> +  static big_integer binary_operation(big_integer &a, big_integer &b, uint32_t (*func)(uint32_t, uint32_t));
[design] омг, ты что, олдфаг? курс по сплюсам все таки, юзай `std::function`

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  while (value.size() > 1 && !value.back()) {
[design] неявные касты на самом деле неоч, плохо читаются, может лучше `== 0`?

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    s.push_back((char) ((tmp % 10).value[0] + '0'));
[design] C-like касты убери, пожалуйста

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  __uint128_t dividend = ((static_cast<__uint128_t>(a.value[a.value.size() - 1]) << 64) |
[design] gcc-dependent  -- не круто ))) `__uint128_t` нет в стандарте (даже всякие `uint32/64_t` вольны быть не реализованными, но 128 есть только в gcc)

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  __uint128_t dividend = ((static_cast<__uint128_t>(a.value[a.value.size() - 1]) << 64) |
Note другому проверяющему: на работу метода не смотрел

2020-06-30 07:52 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return big_integer::binary_operation((big_integer &) a, (big_integer &) b,
[design] C-like касты, к тому же (const&) -> (&) (const_cast), точно не нужно тут использовать

2020-06-30 08:58 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  sign(a < 0), value({a < 0 ? static_cast<uint32_t>(-static_cast<int64_t>(a)) : static_cast<uint32_t>(a)}) {}
fixed

2020-06-30 09:55 UTC, Dave11ar commented on bigint/big_integer.h
> +  static big_integer binary_operation(big_integer &a, big_integer &b, uint32_t (*func)(uint32_t, uint32_t));
fixed, просто сделал членом класса

2020-06-30 10:06 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  while (value.size() > 1 && !value.back()) {
fixed

2020-06-30 10:15 UTC, Dave11ar commented on bigint/big_integer.cpp
> +    s.push_back((char) ((tmp % 10).value[0] + '0'));
fixed

2020-06-30 10:20 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  __uint128_t dividend = ((static_cast<__uint128_t>(a.value[a.value.size() - 1]) << 64) |
fixed

2020-06-30 10:26 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  return big_integer::binary_operation((big_integer &) a, (big_integer &) b,
fixed

2020-07-01 15:15 UTC, kt-cpp commented on bigint/big_integer.h
> +  static big_integer binary_operation(big_integer &a, big_integer &b, uint32_t (*func)(uint32_t, uint32_t));
Имелось ввиду то, что `uint32_t (*func)(uint32_t, uint32_t)` надо заменить.

2020-07-01 16:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  uint64_t divider = static_cast<uint64_t>(b.value.back());
[minor] Здесь static_cast не нужен, каст и так произойдет. А читать будет удобнее.

2020-07-01 16:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return a - (a / b) * b;
[note] Можно оптимизировать и сделать функцию, которая будет возвращать пару из частного и остатка.

2020-07-01 16:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  uint32_t new_sign = func(sign, b.sign);
Результат `^ 0` и `^ (-0)` будет отличаться знаком.

2020-07-01 16:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +bool operator>=(big_integer const &a, big_integer const &b) {
Этот оператор можно реализовать более оптимально, за один проход по векторам.

2020-07-01 16:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    s.push_back((char) ((tmp % 10).value[0] + '0'));
не везде, например в строке 158

2020-07-01 16:50 UTC, kt-cpp requested changes

2020-07-01 16:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  a.sign = false;
Не очевидно, зачем строка 154 после проверки на строке 146

2020-07-01 18:08 UTC, Dave11ar commented on bigint/big_integer.cpp
> +    s.push_back((char) ((tmp % 10).value[0] + '0'));
fixed

2020-07-01 18:09 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  a.sign = false;
fixed

2020-07-01 18:55 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  uint64_t divider = static_cast<uint64_t>(b.value.back());
fixed

2020-07-01 20:31 UTC, Dave11ar commented on bigint/big_integer.cpp
> +bool operator>=(big_integer const &a, big_integer const &b) {
fixed

2020-07-01 20:34 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  uint32_t new_sign = func(sign, b.sign);
Поменял `remove_zero` на `normalize`, который удаляет ведущие нули и не допускает `-0`

2020-07-01 21:41 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  return a - (a / b) * b;
fixed

2020-07-01 22:35 UTC, Dave11ar commented on bigint/big_integer.h
> +  static big_integer binary_operation(big_integer &a, big_integer &b, uint32_t (*func)(uint32_t, uint32_t));
fixed

2020-07-04 20:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  sign(a < 0), value({a < 0 ? static_cast<uint32_t>(-static_cast<int64_t>(a)) : static_cast<uint32_t>(a)}) {}
там правда два пробела после `=`, но ладно

2020-07-04 21:01 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  uint64_t divider = static_cast<uint64_t>(b.value.back());
Было бы здорово поправить это во всех подобных местах, а не только в этой строке. Например, в следующей же строке то же самое.

2020-07-04 21:02 UTC, kt-cpp commented on bigint/big_integer.cpp
> +bool operator>=(big_integer const &a, big_integer const &b) {
:+1: 

Вообще, тут я хотел `!(a < b)`, но так даже лучше :)

2020-07-04 21:22 UTC, kt-cpp requested changes
Почти ок

2020-07-04 21:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  reverse(a.value.begin(), a.value.end());
[minor] `a.erase(...)`? К итераторам можно прибавлять числа, чтобы убрать нужное число элементов.

2020-07-04 21:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  reverse(a.value.begin(), a.value.end());
[minor] у вектора есть вот такой хороший метод: `iterator insert(const_iterator pos, size_type count, const T& value);`

2020-07-04 21:22 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
А зачем non-const версия `size()`?

2020-07-05 20:49 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  uint64_t divider = static_cast<uint64_t>(b.value.back());
я пробежался по всем кастам и убрал все(я надеюсь) лишние

2020-07-05 20:59 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  reverse(a.value.begin(), a.value.end());
fixed, и правда вышло гораздо лучше

2020-07-05 21:05 UTC, Dave11ar commented on bigint/big_integer.cpp
> +  reverse(a.value.begin(), a.value.end());
fixed

2020-07-05 21:07 UTC, Dave11ar commented on bigint/big_integer.cpp
>  }
fixed, и правда не нужна, не помню зачем ее добавил

2020-07-06 17:44 UTC, kt-cpp approved these changes

2020-07-06 17:45 UTC, merged