Bigint-opt
Dave11ar/first-term pull request #4
Opened 2020-06-29 16:57 UTC by Dave11ar

2020-06-30 15:06 UTC, kt-cpp requested changes
* Не вижу COW вообще
* SO должно быть не на 1 элемент, а на массив константного размер, который при это ещё можно менять сменой одной константы в коде. Советую для этого `constexpr` переменные. Обычно берут размер так, чтобы размер альтернатив union был равен(т.е. в данном случае массив размера 2, ибо два `uint32_t` по размеру как один указатель. Но ничто не мешает больше 

Ну и вследствие косяков выше код особо не смотрелся

2020-07-01 17:35 UTC, kt-cpp requested changes
В целом уже очень похоже на правду. Но слишком много COW логики реализовано внутри SO хранилища. Нужно унести туда больше логики в виде статических и не очень функций. Из простых примеров `unique`, `ensure_unique` можно придумать

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +const size_t MAX_SMALL = 2;
Лучше `constexpr` и сделать частью класса buffer, нет нужды торчать наружу

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +  bool sign;
Зачем он тут?

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +  size_t const& get_size() const {
[minor] Нет смысла возвращать по ссылке

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +  }
[note] Почему не реализовать всё через swap trick?

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +        }
У вектор есть конструктор от двух итераторов, коими могут быть и указатели

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +        shared_data = new shared_container<T>(tmp);
Кажется не очень строгие гарантии получились

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +      small_data[i].~T();
Тут должно быть `i - 1`

2020-07-01 17:35 UTC, kt-cpp commented on bigint-optimized/shared_container.h
> +#endif //BIGINT__SHARED_CONTAINER_H_
Что это за файл?)

2020-07-01 23:39 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +  bool sign;
fixed

2020-07-01 23:40 UTC, Dave11ar commented on bigint-optimized/shared_container.h
> +#endif //BIGINT__SHARED_CONTAINER_H_
я зачем то из него убрал `shared_container` в `buffer`))

2020-07-01 23:40 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +      small_data[i].~T();
fixed

2020-07-01 23:42 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +        }
fixed

2020-07-02 00:52 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +  }
fixed

2020-07-02 00:54 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +  size_t const& get_size() const {
fixed

2020-07-02 00:57 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +const size_t MAX_SMALL = 2;
fixed

2020-07-02 09:58 UTC, kt-cpp commented on bigint-optimized/shared_container.h
> +  }
Мне не нравится `unique`, который меняет счётчики. Это не то, что я ожидаю от его контракта. Раздели их на две функции: одна проверяет уникальность, а вторая уже что-то меняет. Например можно сделать функцию, которая в случае неуникальности уменьшает счётчик и возвращает указатель на копию объекта, а иначе просто `this`

2020-07-02 09:58 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +  bool sign;
Не вижу фиксов, кажется хранения знака это вообще не часть контейнера

2020-07-02 10:04 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +      small_data[i].~T();
Ты выпилил деструктор вообще и  теперьу тебя данные утекают)

2020-07-02 10:08 UTC, kt-cpp requested changes
Осталось совсем немного

2020-07-02 10:08 UTC, kt-cpp commented on bigint-optimized/shared_container.h
> +  }
Так же можно вынести функцию, которая уменьшает счётчик на 1 и если что удаляет данные по указателю

2020-07-02 11:22 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +  bool sign;
fixed

2020-07-02 11:27 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +      small_data[i].~T();
если честно не особо помню зачем я его убрал лол, fixed

2020-07-02 11:38 UTC, Dave11ar commented on bigint-optimized/shared_container.h
> +  }
fixed

2020-07-02 17:00 UTC, kt-cpp requested changes
Если ещё несколько необязательных [note], если есть желание можем выказать

2020-07-02 17:00 UTC, kt-cpp commented on bigint-optimized/shared_container.h
> +  shared_container<T>* make_unique() {
[minor] `<T>` тут писать не нужно, так мы уже внутри класса

2020-07-02 17:00 UTC, kt-cpp commented on bigint-optimized/buffer.h
> +        shared_container<T>* g_tmp = new shared_container<T>(tmp);
[note] Можно было бы избежать лишних копирований, сделав соотв конструктор у шаред

2020-07-02 17:00 UTC, kt-cpp commented on bigint-optimized/shared_container.h
> +  void clear_mem() {
[minor] Нейминг не совсем соответствует тому, что она делает. Она скорее освобождает от раздельного владения

2020-07-02 19:09 UTC, Dave11ar commented on bigint-optimized/shared_container.h
> +  void clear_mem() {
fixed(скорее всего)

2020-07-02 19:10 UTC, Dave11ar commented on bigint-optimized/shared_container.h
> +  shared_container<T>* make_unique() {
fixed

2020-07-02 20:13 UTC, Dave11ar commented on bigint-optimized/buffer.h
> +        shared_container<T>* g_tmp = new shared_container<T>(tmp);
В общем я решил убрать темплейты ибо в самом бигинте я везде все равно использую `uint32_t` и игра по затыканию всех дыр в буффере видимо не стоит свеч

2020-07-02 22:43 UTC, kt-cpp approved these changes

2020-07-02 22:44 UTC, merged